2024-11-12 11:04:02.894 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:04:02.898 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:04:02.899 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:04:02.899 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:04:14.162 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:04:14.163 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:04:14.164 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:04:14.164 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:04:14.233 - INFO - root - main.py:70 - load_test_data - Test data successfully loaded and saved
2024-11-12 11:05:23.197 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:05:23.198 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:05:23.199 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:05:23.199 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:10.233 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:10.234 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:10.234 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:10.235 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:13.209 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:13.210 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:13.211 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:13.211 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:19.504 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:19.505 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:19.505 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:19.506 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:21.804 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:21.805 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:21.806 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:21.807 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:21.872 - INFO - root - main.py:70 - load_test_data - Test data successfully loaded and saved
2024-11-12 11:28:31.223 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:31.223 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:31.224 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:31.224 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:37.381 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:37.381 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:37.382 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:37.382 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:38.730 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:38.730 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:38.730 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:38.731 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:55.900 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:55.900 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:55.901 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:55.901 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:28:56.612 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:28:56.612 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:28:56.613 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:28:56.614 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:02.548 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:02.549 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:02.549 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:02.549 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:03.292 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:03.293 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:03.293 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:03.293 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:07.246 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:07.247 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:07.247 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:07.248 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:07.794 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:07.795 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:07.795 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:07.796 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:10.299 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:10.299 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:10.299 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:10.300 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:10.897 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:10.898 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:10.898 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:10.899 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:13.028 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:13.030 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:13.030 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:13.031 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:13.614 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:13.615 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:13.615 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:13.615 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:13.619 - INFO - root - main.py:335 - main - Открыта вкладка генерации отчетов
2024-11-12 11:29:15.750 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:15.751 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:15.751 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:15.752 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:15.757 - INFO - root - main.py:335 - main - Открыта вкладка генерации отчетов
2024-11-12 11:29:16.429 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:16.431 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:16.431 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:16.431 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:22.492 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:22.492 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:22.493 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:22.493 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:29:39.984 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:29:39.985 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:29:39.985 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:29:39.985 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:30:33.839 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:30:33.841 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:30:33.841 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:30:33.841 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:35:01.701 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:35:01.703 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:35:01.703 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:35:01.703 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:35:13.484 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:35:13.485 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:35:13.485 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:35:13.486 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:35:23.012 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:35:23.013 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:35:23.013 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:35:23.014 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:35:30.300 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:35:30.301 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:35:30.301 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:35:30.302 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:35:35.509 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:35:35.511 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:35:35.511 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:35:35.511 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:35:44.417 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:35:44.419 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:35:44.420 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:35:44.420 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:53:36.865 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:53:36.866 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:53:36.867 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:53:36.867 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:53:40.360 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:53:40.360 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:53:40.361 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:53:40.361 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:53:47.836 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:53:47.837 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:53:47.837 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:53:47.837 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:53:49.021 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:53:49.022 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:53:49.022 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:53:49.022 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:53:58.030 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:53:58.031 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:53:58.031 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:53:58.031 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:53:58.846 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:53:58.847 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:53:58.847 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:53:58.848 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:54:08.491 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:54:08.492 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:54:08.492 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:54:08.493 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:54:11.798 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:54:11.799 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:54:11.799 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:54:11.800 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:54:28.149 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:54:28.150 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:54:28.150 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:54:28.150 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:54:28.826 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:54:28.826 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:54:28.827 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:54:28.827 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:02.741 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:02.741 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:02.742 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:02.742 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:03.405 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:03.405 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:03.405 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:03.406 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:14.875 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:14.875 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:14.875 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:14.876 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:15.475 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:15.476 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:15.476 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:15.477 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:25.240 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:25.241 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:25.241 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:25.241 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:25.862 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:25.863 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:25.863 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:25.864 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:33.389 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:33.390 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:33.391 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:33.391 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:33.954 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:33.954 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:33.955 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:33.955 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:36.277 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:36.278 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:36.278 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:36.279 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:36.780 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:36.781 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:36.781 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:36.782 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:36.838 - INFO - root - main.py:335 - main - Открыта вкладка генерации отчетов
2024-11-12 11:55:43.452 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:43.454 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:43.454 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:43.455 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:43.523 - INFO - root - main.py:335 - main - Открыта вкладка генерации отчетов
2024-11-12 11:55:48.168 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:55:48.169 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:55:48.170 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:55:48.170 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:55:48.235 - INFO - root - main.py:335 - main - Открыта вкладка генерации отчетов
2024-11-12 11:56:00.375 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:56:00.376 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:56:00.376 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:56:00.377 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:56:05.683 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:56:05.684 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:56:05.684 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:56:05.685 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 11:56:06.193 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 11:56:06.194 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 11:56:06.195 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 11:56:06.195 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:06:33.197 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:06:33.198 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:06:33.198 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:06:33.199 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:06:46.723 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:06:46.724 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:06:46.725 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:06:46.725 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:06:49.036 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:06:49.037 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:06:49.038 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:06:49.039 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:10:54.913 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:10:54.914 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:10:54.914 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:10:54.914 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:10:57.819 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:10:57.820 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:10:57.821 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:10:57.821 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:31:54.986 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:31:54.987 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:31:54.987 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:31:54.988 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:32:00.806 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:32:00.806 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:32:00.807 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:32:00.807 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:32:00.854 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 12:32:03.261 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:32:03.262 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:32:03.262 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:32:03.262 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:32:17.862 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:32:17.864 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:32:17.864 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:32:17.864 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:34:47.864 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:34:47.865 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:34:47.866 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:34:47.866 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:34:54.357 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:34:54.358 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:34:54.358 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:34:54.359 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:34:56.352 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:34:56.352 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:34:56.353 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:34:56.353 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:35:01.193 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:35:01.193 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:35:01.193 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:35:01.194 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:38:08.978 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:38:08.978 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:38:08.979 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:38:08.980 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:38:15.851 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:38:15.852 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:38:15.853 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:38:15.853 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:38:17.390 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:38:17.391 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:38:17.391 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:38:17.392 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:38:23.766 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:38:23.767 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:38:23.767 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:38:23.768 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:38:27.362 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:38:27.363 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:38:27.364 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:38:27.364 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:40:22.647 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:40:22.647 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:40:22.648 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:40:22.648 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:40:27.172 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:40:27.173 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:40:27.173 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:40:27.173 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:40:29.256 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:40:29.257 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:40:29.258 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:40:29.258 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:40:34.914 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:40:34.915 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:40:34.915 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:40:34.916 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:42:28.140 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:42:28.141 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:42:28.141 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:42:28.141 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:42:34.195 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:42:34.196 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:42:34.196 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:42:34.197 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:42:35.568 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:42:35.569 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:42:35.570 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:42:35.571 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:43:44.960 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:43:44.961 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:43:44.962 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:43:44.962 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:43:52.057 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:43:52.058 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:43:52.059 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:43:52.059 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:43:53.267 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:43:53.268 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:43:53.269 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:43:53.269 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:44:55.214 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:44:55.214 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:44:55.215 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:44:55.215 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:44:59.595 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:44:59.596 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:44:59.597 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:44:59.597 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:45:02.191 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:45:02.192 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:45:02.192 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:45:02.193 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:45:45.872 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:45:45.872 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:45:45.873 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:45:45.873 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:45:47.086 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:45:47.087 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:45:47.088 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:45:47.089 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:45:54.847 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:45:54.848 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:45:54.848 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:45:54.848 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:45:55.440 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:45:55.441 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:45:55.442 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:45:55.443 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:18.421 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:18.422 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:18.422 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:18.423 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:30.506 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:30.507 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:30.507 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:30.508 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:33.397 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:33.398 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:33.399 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:33.400 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:38.103 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:38.103 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:38.104 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:38.105 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:38.150 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 12:50:41.283 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:41.284 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:41.285 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:41.287 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:43.728 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:43.729 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:43.729 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:43.730 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:46.426 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:46.426 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:46.427 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:46.428 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:48.298 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:48.298 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:48.299 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:48.299 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:50.652 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:50.654 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:50.655 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:50.656 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:53.486 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:53.488 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:53.489 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:53.490 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:53.533 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 12:50:56.825 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:56.826 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:56.826 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:56.827 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:58.366 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:58.368 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:58.369 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:58.369 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:50:59.071 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:50:59.072 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:50:59.073 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:50:59.074 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:51:00.313 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:51:00.315 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:51:00.315 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:51:00.317 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:51:01.192 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:51:01.194 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:51:01.195 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:51:01.196 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:51:04.217 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:51:04.220 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:51:04.221 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:51:04.221 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:51:17.030 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:51:17.031 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:51:17.031 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:51:17.031 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:54:50.106 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:54:50.107 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:54:50.107 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:54:50.107 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:54:54.998 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:54:54.999 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:54:54.999 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:54:55.000 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:54:55.040 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 12:54:57.238 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:54:57.239 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:54:57.240 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:54:57.240 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:54:58.555 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:54:58.555 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:54:58.556 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:54:58.556 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:54:59.346 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:54:59.347 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:54:59.348 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:54:59.348 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:02.503 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:02.504 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:02.504 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:02.504 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:03.118 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:03.118 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:03.119 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:03.119 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:07.379 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:07.380 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:07.380 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:07.380 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:13.279 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:13.280 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:13.280 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:13.281 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:19.499 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:19.500 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:19.501 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:19.501 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:24.345 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:24.345 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:24.347 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:24.347 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:26.414 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:26.415 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:26.415 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:26.415 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:27.095 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:27.095 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:27.096 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:27.096 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:55:32.065 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:55:32.065 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:55:32.066 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:55:32.066 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:56:57.520 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:56:57.521 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:56:57.522 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:56:57.522 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:00.766 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:00.768 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:00.769 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:00.771 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:00.825 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 12:57:03.339 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:03.341 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:03.342 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:03.343 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:11.888 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:11.890 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:11.890 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:11.890 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:12.531 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:12.532 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:12.532 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:12.533 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:13.934 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:13.935 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:13.935 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:13.935 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:14.486 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:14.488 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:14.488 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:14.488 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:17.333 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:17.334 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:17.334 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:17.336 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:20.553 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:20.554 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:20.555 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:20.555 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:25.666 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:25.669 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:25.669 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:25.669 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:25.709 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 12:57:27.630 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:27.631 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:27.632 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:27.632 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:34.096 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:34.097 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:34.097 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:34.098 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 12:57:36.930 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 12:57:36.932 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 12:57:36.933 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 12:57:36.934 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:28:25.735 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:28:25.736 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:28:25.737 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:28:25.737 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:28:30.033 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:28:30.034 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:28:30.034 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:28:30.034 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:28:30.075 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 13:28:31.480 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:28:31.481 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:28:31.482 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:28:31.483 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:28:34.017 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:28:34.018 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:28:34.018 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:28:34.018 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:28:34.944 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:28:34.945 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:28:34.947 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:28:34.947 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:28:39.023 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:28:39.024 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:28:39.025 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:28:39.026 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:06.221 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:06.222 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:06.222 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:06.223 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:10.492 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:10.493 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:10.493 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:10.494 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:10.537 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 13:37:13.263 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:13.263 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:13.264 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:13.264 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:14.236 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:14.238 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:14.238 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:14.238 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:14.891 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:14.891 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:14.892 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:14.892 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:15.599 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:15.601 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:15.602 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:15.602 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:16.191 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:16.192 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:16.193 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:16.194 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:18.618 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:18.619 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:18.619 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:18.619 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:33.398 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:33.399 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:33.399 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:33.400 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:35.757 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:35.758 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:35.759 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:35.759 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:36.403 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:36.405 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:36.407 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:36.407 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:40.053 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:40.054 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:40.055 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:40.056 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:46.666 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:46.666 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:46.667 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:46.667 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:47.991 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:47.993 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:47.993 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:47.994 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:48.544 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:48.544 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:48.545 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:48.546 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:50.006 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:50.007 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:50.007 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:50.008 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:50.530 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:50.531 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:50.532 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:50.533 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:55.720 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:55.721 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:55.723 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:55.723 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:57.656 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:57.657 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:57.657 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:57.658 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:37:58.501 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:37:58.502 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:37:58.503 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:37:58.504 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:38:00.825 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:38:00.826 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:38:00.826 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:38:00.827 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:38:00.831 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_133800.pdf
2024-11-12 13:38:00.833 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 13:38:00.834 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_133800.pdf, sections=['Базовая информация', 'Типы данных', 'Дубликаты', 'Статистика', 'Пропущенные значения']
2024-11-12 13:38:00.849 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_133800.pdf
2024-11-12 13:38:01.287 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:38:01.302 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:38:01.304 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 13:54:27.350 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:27.351 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:27.352 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:27.352 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:29.983 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:29.984 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:29.984 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:29.984 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:30.022 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 13:54:31.413 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:31.414 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:31.416 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:31.416 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:34.175 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:34.175 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:34.175 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:34.176 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:36.807 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:36.808 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:36.808 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:36.809 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:39.117 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:39.120 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:39.121 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:39.121 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:40.843 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:40.844 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:40.845 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:40.845 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:40.853 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_135440.pdf
2024-11-12 13:54:40.856 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 13:54:40.857 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_135440.pdf, sections=['Базовая информация', 'Типы данных', 'Пропущенные значения', 'Дубликаты', 'Статистика']
2024-11-12 13:54:40.870 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_135440.pdf
2024-11-12 13:54:40.871 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:54:40.875 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:54:40.877 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 13:54:45.090 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:45.091 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:45.092 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:45.093 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:49.804 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:49.805 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:49.806 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:49.806 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:49.850 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 13:54:52.651 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:52.652 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:52.652 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:52.652 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:58.048 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:58.049 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:58.049 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:58.050 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:54:58.974 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:54:58.975 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:54:58.975 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:54:58.976 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:00.121 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:00.122 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:00.122 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:00.122 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:00.699 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:00.700 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:00.701 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:00.701 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:01.598 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:01.599 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:01.599 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:01.600 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:02.317 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:02.318 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:02.318 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:02.319 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:03.724 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:03.724 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:03.724 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:03.725 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:04.246 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:04.246 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:04.246 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:04.247 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:05.900 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:05.901 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:05.902 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:05.903 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:06.422 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:06.424 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:06.425 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:06.425 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:08.714 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:55:08.715 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:55:08.715 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:55:08.716 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:55:08.724 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_135508.pdf
2024-11-12 13:55:08.726 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 13:55:08.726 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_135508.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 13:55:08.730 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_135508.pdf
2024-11-12 13:55:08.731 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:55:08.734 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:55:08.735 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 13:57:22.889 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:22.889 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:22.890 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:22.890 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:25.687 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:25.690 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:25.690 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:25.691 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:25.734 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 13:57:27.458 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:27.460 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:27.460 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:27.460 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:28.136 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:28.137 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:28.139 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:28.140 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:28.931 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:28.932 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:28.932 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:28.933 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:29.524 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:29.525 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:29.526 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:29.527 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:30.280 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:30.281 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:30.281 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:30.282 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:30.885 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:30.886 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:30.887 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:30.887 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:31.468 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:31.469 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:31.470 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:31.471 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:32.139 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:32.140 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:32.140 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:32.140 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:32.729 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:32.730 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:32.730 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:32.730 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:33.494 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:33.495 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:33.497 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:33.498 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:34.373 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:34.376 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:34.377 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:34.377 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:36.178 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:57:36.179 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:57:36.180 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:57:36.181 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:57:36.187 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_135736.pdf
2024-11-12 13:57:36.189 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 13:57:36.189 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_135736.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 13:57:36.192 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_135736.pdf
2024-11-12 13:57:36.193 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:57:36.196 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:57:36.197 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 13:59:16.215 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:16.216 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:16.217 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:16.217 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:19.024 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:19.024 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:19.025 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:19.026 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:19.066 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 13:59:22.256 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:22.257 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:22.258 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:22.258 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:22.966 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:22.967 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:22.968 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:22.969 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:23.565 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:23.566 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:23.566 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:23.567 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:24.144 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:24.145 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:24.145 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:24.145 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:24.991 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:24.992 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:24.992 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:24.993 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:26.540 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 13:59:26.540 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 13:59:26.541 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 13:59:26.541 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 13:59:26.545 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_135926.pdf
2024-11-12 13:59:26.547 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 13:59:26.548 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_135926.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 13:59:26.550 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_135926.pdf
2024-11-12 13:59:26.551 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:59:26.553 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x000001AB9C231DA0>': 'pdf'
2024-11-12 13:59:26.554 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:00:06.037 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:06.038 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:06.039 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:06.039 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:07.796 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:07.797 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:07.799 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:07.799 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:07.850 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 14:00:10.774 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:10.775 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:10.775 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:10.776 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:12.397 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:12.400 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:12.401 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:12.401 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:12.999 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:13.000 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:13.001 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:13.002 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:14.408 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:14.409 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:14.409 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:14.409 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:15.203 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:15.205 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:15.206 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:15.206 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:15.915 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:15.916 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:15.916 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:15.918 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:16.749 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:16.750 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:16.752 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:16.752 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:18.708 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:00:18.709 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:00:18.709 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:00:18.710 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:00:18.716 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_140018.pdf
2024-11-12 14:00:18.718 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:00:18.719 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_140018.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 14:00:18.721 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_140018.pdf
2024-11-12 14:00:18.925 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:00:18.928 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:00:18.929 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:02:47.646 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:47.647 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:47.648 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:47.648 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:49.921 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:49.922 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:49.922 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:49.923 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:49.962 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 14:02:52.258 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:52.259 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:52.260 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:52.260 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:53.136 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:53.137 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:53.137 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:53.138 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:53.842 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:53.843 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:53.844 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:53.845 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:54.609 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:54.609 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:54.609 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:54.610 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:55.322 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:55.322 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:55.323 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:55.323 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:55.972 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:55.973 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:55.973 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:55.974 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:57.519 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:57.520 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:57.520 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:57.520 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:58.894 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:02:58.895 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:02:58.896 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:02:58.896 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:02:58.901 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_140258.pdf
2024-11-12 14:02:58.903 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:02:58.904 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_140258.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 14:02:58.908 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_140258.pdf
2024-11-12 14:02:58.908 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:02:58.910 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:02:58.912 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:03:03.268 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:03:03.269 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:03:03.269 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:03:03.269 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:03:04.164 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:03:04.165 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:03:04.165 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:03:04.166 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:03:05.480 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:03:05.481 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:03:05.481 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:03:05.482 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:03:05.488 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_140305.pdf
2024-11-12 14:03:05.490 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:03:05.491 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_140305.pdf, sections=['Базовая информация', 'Типы данных', 'Пропущенные значения', 'Дубликаты']
2024-11-12 14:03:05.500 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_140305.pdf
2024-11-12 14:03:05.501 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:03:05.503 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:03:05.505 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:04:49.674 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:49.675 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:49.675 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:49.676 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:52.634 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:52.634 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:52.634 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:52.635 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:52.671 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 14:04:53.860 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:53.860 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:53.862 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:53.862 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:55.013 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:55.015 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:55.015 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:55.016 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:55.816 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:55.817 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:55.819 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:55.819 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:56.278 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:56.279 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:56.280 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:56.281 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:56.852 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:56.854 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:56.854 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:56.855 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:59.129 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:59.129 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:59.130 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:59.131 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:04:59.723 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:04:59.724 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:04:59.724 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:04:59.725 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:05:01.216 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:05:01.218 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:05:01.218 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:05:01.218 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:05:01.225 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_140501.pdf
2024-11-12 14:05:01.227 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:05:01.228 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_140501.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 14:05:01.232 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_140501.pdf
2024-11-12 14:05:01.232 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:05:01.235 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:05:01.236 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:28:56.288 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:28:56.289 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:28:56.290 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:28:56.292 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:03.788 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:03.790 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:03.790 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:03.791 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:03.841 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 14:29:06.893 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:06.894 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:06.895 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:06.895 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:07.474 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:07.475 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:07.475 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:07.476 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:08.152 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:08.154 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:08.154 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:08.154 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:09.406 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:09.406 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:09.407 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:09.408 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:11.600 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:11.601 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:11.602 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:11.603 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:12.433 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:12.434 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:12.435 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:12.435 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:13.350 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:13.351 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:13.351 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:13.352 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:15.041 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:15.041 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:15.042 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:15.043 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:15.048 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_142915.pdf
2024-11-12 14:29:15.049 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:29:15.051 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_142915.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 14:29:15.056 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_142915.pdf
2024-11-12 14:29:15.057 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:29:15.060 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:29:15.061 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:29:18.376 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:18.377 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:18.378 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:18.378 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:20.071 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:29:20.073 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:29:20.076 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:29:20.077 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:29:20.085 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_142920.pdf
2024-11-12 14:29:20.088 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:29:20.089 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_142920.pdf, sections=['Базовая информация', 'Типы данных', 'Пропущенные значения']
2024-11-12 14:29:20.095 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_142920.pdf
2024-11-12 14:29:20.096 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:29:20.098 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:29:20.099 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:31:26.069 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:26.070 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:26.070 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:26.071 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:28.162 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:28.162 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:28.163 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:28.163 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:28.207 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 14:31:30.546 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:30.547 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:30.547 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:30.548 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:32.278 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:32.279 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:32.280 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:32.280 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:32.288 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_143132.pdf
2024-11-12 14:31:32.292 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:31:32.293 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_143132.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 14:31:32.298 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_143132.pdf
2024-11-12 14:31:32.300 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:31:32.303 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:31:32.305 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 14:31:34.975 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:34.976 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:34.977 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:34.977 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:36.509 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:36.510 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:36.510 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:36.511 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:37.049 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:37.050 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:37.051 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:37.051 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:37.848 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:37.850 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:37.851 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:37.851 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:38.440 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:38.441 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:38.441 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:38.442 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:39.248 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:39.249 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:39.250 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:39.250 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:39.782 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:39.783 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:39.783 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:39.784 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:41.586 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:41.586 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:41.587 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:41.587 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:42.655 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:42.657 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:42.657 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:42.657 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:45.187 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:45.188 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:45.188 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:45.188 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:46.796 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 14:31:46.798 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 14:31:46.799 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 14:31:46.799 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 14:31:46.803 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_143146.pdf
2024-11-12 14:31:46.807 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 14:31:46.808 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_143146.pdf, sections=['Базовая информация', 'Типы данных', 'Пропущенные значения']
2024-11-12 14:31:46.816 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_143146.pdf
2024-11-12 14:31:46.817 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:31:46.820 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 14:31:46.821 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 15:05:57.714 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:05:57.716 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:05:57.717 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:05:57.717 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:06:07.120 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:06:07.121 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:06:07.121 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:06:07.122 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:06:07.168 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 15:06:10.864 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:06:10.865 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:06:10.865 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:06:10.865 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:08:02.646 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:08:02.647 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:08:02.647 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:08:02.647 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:08:13.697 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:08:13.698 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:08:13.698 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:08:13.699 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:08:16.581 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:08:16.582 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:08:16.583 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:08:16.583 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:08:22.266 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:08:22.266 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:08:22.267 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:08:22.267 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:08:23.878 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:08:23.878 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:08:23.879 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:08:23.880 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:08:30.534 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:08:30.535 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:08:30.536 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:08:30.537 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:08:43.162 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:08:43.162 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:08:43.162 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:08:43.163 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:09:00.004 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:09:00.005 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:09:00.005 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:09:00.006 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:09:02.452 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:09:02.453 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:09:02.454 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:09:02.454 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:09:02.544 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_150902.pdf
2024-11-12 15:09:02.546 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 2 колонок
2024-11-12 15:09:02.546 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_150902.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 15:09:02.549 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_150902.pdf
2024-11-12 15:09:02.550 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 15:09:02.552 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 15:09:02.553 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 15:12:27.524 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:12:27.526 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:12:27.526 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:12:27.526 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:12:31.840 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:12:31.840 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:12:31.841 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:12:31.841 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:12:33.193 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:12:33.195 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:12:33.195 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:12:33.196 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:12:33.203 - INFO - utils.report_generator - report_generator.py:142 - generate_data_report - Создание отчета: C:\automl\reports\reports\report_20241112_151233.pdf
2024-11-12 15:12:33.206 - INFO - root - report_generator.py:34 - _prepare_datatypes - Типы данных успешно преобразованы для 3 колонок
2024-11-12 15:12:33.208 - INFO - utils.report_generator - report_generator.py:46 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\reports\report_20241112_151233.pdf, sections=['Базовая информация', 'Типы данных']
2024-11-12 15:12:33.213 - INFO - utils.report_generator - report_generator.py:111 - generate_report - Сохранение отчета в файл: C:\automl\reports\reports\report_20241112_151233.pdf
2024-11-12 15:12:33.214 - ERROR - utils.report_generator - report_generator.py:120 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
Traceback (most recent call last):
  File "C:\automl\utils\report_generator.py", line 112, in generate_report
    with pd.ExcelWriter(fname, engine='openpyxl') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1221, in __init__
    self.check_extension(ext)
  File "C:\Users\Mih10\anaconda3\envs\automl\Lib\site-packages\pandas\io\excel\_base.py", line 1340, in check_extension
    raise ValueError(f"Invalid extension for engine '{cls.engine}': '{ext}'")
ValueError: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 15:12:33.217 - ERROR - root - report_generator.py:122 - generate_report - Ошибка при генерации отчета: Invalid extension for engine '<property object at 0x00000260FF568AE0>': 'pdf'
2024-11-12 15:12:33.218 - ERROR - utils.report_generator - report_generator.py:151 - generate_data_report - Не удалось создать отчет
2024-11-12 15:17:10.331 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:17:10.332 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:17:10.332 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:17:10.332 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:17:17.861 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:17:17.863 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:17:17.863 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:17:17.864 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:17:21.199 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:17:21.200 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:17:21.200 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:17:21.200 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:17:48.002 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:17:48.003 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:17:48.004 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:17:48.004 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:17:48.640 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:17:48.641 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:17:48.641 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:17:48.641 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:17:51.621 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:17:51.622 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:17:51.622 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:17:51.623 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:17:54.309 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:17:54.310 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:17:54.311 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:17:54.311 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:18:02.928 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:18:02.929 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:18:02.930 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:18:02.930 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:18:12.017 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:18:12.020 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:18:12.022 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:18:12.023 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:18:20.820 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:18:20.821 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:18:20.821 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:18:20.822 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:18:22.000 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:18:22.001 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:18:22.002 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:18:22.003 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:18:22.809 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:18:22.811 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:18:22.811 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:18:22.811 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:18:23.966 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:18:23.969 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:18:23.970 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:18:23.971 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:18:24.063 - INFO - utils.report_generator - report_generator.py:168 - generate_data_report - Создание отчета: C:\automl\reports\report_20241112_151824.xlsx
2024-11-12 15:18:24.065 - INFO - root - report_generator.py:37 - _prepare_datatypes - Типы данных успешно преобразованы для 2 колонок
2024-11-12 15:18:24.065 - INFO - utils.report_generator - report_generator.py:49 - generate_report - Начало генерации отчета. Параметры: fname=C:\automl\reports\report_20241112_151824.xlsx, sections=['Базовая информация', 'Типы данных']
2024-11-12 15:18:24.067 - INFO - utils.report_generator - report_generator.py:114 - generate_report - Сохранение отчета в файл: C:\automl\reports\report_20241112_151824.xlsx
2024-11-12 15:18:24.113 - INFO - root - report_generator.py:142 - generate_report - Отчет успешно сохранен: C:\automl\reports\report_20241112_151824.xlsx
2024-11-12 15:18:24.114 - INFO - utils.report_generator - report_generator.py:184 - generate_data_report - Отчет успешно создан: C:\automl\reports\report_20241112_151824.xlsx
2024-11-12 15:18:26.492 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:18:26.493 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:18:26.494 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:18:26.494 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:24:01.363 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:24:01.363 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:24:01.364 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:24:01.365 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:26:26.535 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:26:26.536 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:26:26.537 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:26:26.537 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:26:29.181 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:26:29.182 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:26:29.182 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:26:29.183 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:26:33.796 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:26:33.797 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:26:33.797 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:26:33.797 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:26:33.846 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 15:26:36.165 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:26:36.166 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:26:36.166 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:26:36.166 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:26:39.553 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:26:39.553 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:26:39.554 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:26:39.554 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:26:51.260 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:26:51.260 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:26:51.261 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:26:51.261 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:26:52.466 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:26:52.466 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:26:52.467 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:26:52.468 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:27:16.884 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:27:16.885 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:27:16.886 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:27:16.886 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:27:20.956 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:27:20.957 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:27:20.957 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:27:20.957 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:27:27.318 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:27:27.319 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:27:27.319 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:27:27.319 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:27:29.131 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:27:29.133 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:27:29.133 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:27:29.133 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:02.693 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:02.693 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:02.694 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:02.695 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:07.006 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:07.007 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:07.007 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:07.007 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:08.742 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:08.743 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:08.744 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:08.745 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:08.791 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 15:38:13.392 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:13.393 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:13.393 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:13.393 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:16.346 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:16.347 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:16.348 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:16.349 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:26.936 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:26.937 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:26.937 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:26.938 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:39.494 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:39.495 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:39.496 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:39.496 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:39.544 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 15:38:43.429 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:43.430 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:43.430 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:43.430 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:38:45.629 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:38:45.629 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:38:45.630 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:38:45.630 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:39:02.237 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:39:02.238 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:39:02.239 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:39:02.239 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:39:07.894 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:39:07.895 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:39:07.896 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:39:07.897 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:39:11.669 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:39:11.669 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:39:11.670 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:39:11.670 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:39:11.809 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:39:11.810 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:39:11.810 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:39:11.811 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:56:58.655 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:56:58.656 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:56:58.656 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:56:58.656 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:57:01.472 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:57:01.473 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:57:01.473 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:57:01.474 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:57:02.542 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:57:02.543 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:57:02.543 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:57:02.543 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:57:03.106 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:57:03.108 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:57:03.108 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:57:03.109 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:57:04.203 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:57:04.205 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:57:04.205 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:57:04.205 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:57:04.249 - INFO - root - data_loader.py:173 - load_test_data - Test data successfully loaded and saved
2024-11-12 15:57:07.663 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:57:07.664 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:57:07.665 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:57:07.666 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
2024-11-12 15:57:08.623 - INFO - root - logging_config.py:49 - setup_logging - ==================================================
2024-11-12 15:57:08.624 - INFO - root - logging_config.py:50 - setup_logging - Логирование инициализировано успешно
2024-11-12 15:57:08.624 - INFO - root - logging_config.py:51 - setup_logging - Тестовая русская строка
2024-11-12 15:57:08.624 - INFO - root - logging_config.py:52 - setup_logging - ==================================================
